### ISSUE TITLE
removeHeaders: undefined is not a function

### ISSUE THREAD

**Issue by skerit** [radekstepan/nzb-grabber-js#5]
Something going wrong here:

```
TypeError: undefined is not a function
    at removeHeaders (/home/skerit/projecten/tapeless-io/node_modules/nzb-grabber-js/src/nntp.coffee:149:34)
    at NNTPWorker.onData (/home/skerit/projecten/tapeless-io/node_modules/nzb-grabber-js/src/nntp.coffee:176:51)
    at Socket.<anonymous> (/home/skerit/projecten/tapeless-io/node_modules/nzb-grabber-js/src/nntp.coffee:3:61)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:510:20)
```

**Comment by radekstepan** [comment]
Do you have a particular NZB I can test this on? If it is something private, you can send me it via email.

**Comment by radekstepan** [comment]
OK, have bumped up the dependencies and can see the error myself. Investigating...
